---

server:
  port: 8070

portal:
  conductor:
    conductor-root-uri: http://localhost:8080/api/
  bitbucket:
    username: some-bitbucket-username
    password: some-bitbucket-password
    team-name: some-bitbucket-team-name
  cloudfoundry:
    api-host: api.run.pivotal.io
    apps-manager-host: console.run.pivotal.io
    organization: some-cloudfoundry-organization
    username: some-cloudfoundry-username
    password: some-cloudfoundry-password
    log-drain-url: some-cloudfoundry-log-drain-url
    domain: some-cloudfoundry-domain
  concourse:
    api-host: https://ci.some-domain
    team-name: some-concourse-team-name
    username: some-concourse-username
    password: some-concourse-password
    should-expose-pipeline: false
  github:
    username: some-github-username
    token: some-github-token
    organization-name: some-github-organization-name
  jira:
    username: some-username
    password: some-password
    api-url: some-api-url
    account-id: some-account-id
  template:
    config:
      fake-key: fake-value
  tracker:
    api-key: some-tracker-api-key
    account-id: -1
