---

server:
  port: 8070

portal:
  conductor:
    conductor-root-uri: http://localhost:8080/api/
  bitbucket:
    username: some-bitbucket-username
    password: some-bitbucket-password
    team-name: some-bitbucket-team-name
  cloudfoundry:
    foundations:
      default:
        api-host: api.run.pivotal.io
        apps-manager-host: console.run.pivotal.io
        organization: some-cloudfoundry-organization
        username: some-cloudfoundry-username
        password: some-cloudfoundry-password
        domain: some-cloudfoundry-domain
        skip-ssl-validation: false
  concourse:
    api-host: https://ci.some-domain
    team-name: some-concourse-team-name
    username: some-concourse-username
    password: some-concourse-password
    should-expose-pipeline: false
  github:
    username: some-github-username
    token: some-github-token
    organization-name: some-github-organization-name
  jira:
    username: some-username
    password: some-password
    api-url: some-api-url
    account-id: some-account-id
  template:
    config:
      fake-key: fake-value
  tracker:
    api-key: some-tracker-api-key
    account-id: -1

---
spring:
  profiles: cfdev

portal:
  cloudfoundry:
    foundations:
      default:
        api-host: api.dev.cfdev.sh
        apps-manager-host: apps.dev.cfdev.sh
        organization: cfdev-org
        username: admin
        password: admin
        domain: dev.cfdev.sh
        skip-ssl-validation: true
      east:
        api-host: api.dev.cfdev.sh
        apps-manager-host: apps.dev.cfdev.sh
        organization: cfdev-org
        username: admin
        password: admin
        domain: dev.cfdev.sh
        skip-ssl-validation: true
      west:
        api-host: api.dev.cfdev.sh
        apps-manager-host: apps.dev.cfdev.sh
        organization: cfdev-org
        username: admin
        password: admin
        domain: dev.cfdev.sh
        skip-ssl-validation: true
logging:
  level:
    cloudfoundry-client: debug

---
spring:
  profiles: docker

portal:
  concourse:
    api-host: http://localhost:8200
    team-name: main
    username: test
    password: test
    should-expose-pipeline: true
